# Generated by Django 5.1.2 on 2025-01-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=150)),
                ('com_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('com_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('com_status', models.BooleanField(default=True)),
                ('com_created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(max_length=150)),
                ('com_password', models.CharField(default='defaultpassword123', max_length=150)),
            ],
            options={
                'db_table': 'qrjump_companies_storage',
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('superadmin_name', models.CharField(max_length=100)),
                ('superadmin_email', models.EmailField(max_length=254)),
                ('superadmin_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('superadmin_password', models.CharField(max_length=255)),
                ('superadmin_status', models.BooleanField(default=True)),
                ('superadmin_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_kh_name', models.CharField(max_length=150)),
                ('br_en_name', models.CharField(max_length=150)),
                ('br_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('br_password', models.CharField(blank=True, max_length=150, null=True)),
                ('br_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('br_status', models.BooleanField(default=True)),
                ('br_created_at', models.DateTimeField(auto_now_add=True)),
                ('com_id', models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='app.company')),
            ],
            options={
                'db_table': 'qrjump_branches_storage',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, max_length=150, null=True)),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('staff_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('staff_position', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_status', models.BooleanField(default=True)),
                ('staff_created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('staff_telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('staff_user_pin', models.CharField(blank=True, max_length=8, null=True)),
                ('branches', models.ManyToManyField(db_table='qrjump_staff_users_branches', related_name='staff', to='app.branch')),
                ('com_id', models.ForeignKey(blank=True, db_column='com_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='app.company')),
            ],
            options={
                'db_table': 'qrjump_staff_users_storage',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('th_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('th_telegram_id', models.BigIntegerField()),
                ('th_datetime', models.DateTimeField(auto_now_add=True)),
                ('th_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('th_currency', models.CharField(max_length=10)),
                ('th_payment_type', models.CharField(max_length=50)),
                ('th_created_at', models.DateTimeField(auto_now_add=True)),
                ('br_id', models.ForeignKey(db_column='br_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.branch')),
                ('com_id', models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.company')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.staff')),
            ],
            options={
                'db_table': 'qrjump_transactions_history_storage',
            },
        ),
    ]
