# Generated by Django 5.1.2 on 2025-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='branches',
            field=models.ManyToManyField(db_table='qrjump_superadmin_branches', related_name='superadmins', to='app.branch'),
        ),
    ]
