# Generated by Django 5.1.2 on 2025-02-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=150)),
                ('sp_created_at', models.DateTimeField(auto_now_add=True)),
                ('com_id', models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.CASCADE, related_name='statispayment', to='app.company')),
            ],
            options={
                'db_table': 'qrjump_static_payments_storage',
            },
        ),
    ]
