# Generated by Django 5.1.2 on 2025-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_superadmin_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='superadmin_branches', to='app.branch'),
        ),
    ]
