# Generated by Django 5.1.2 on 2025-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staticpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankcredentials',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bankcredentials',
            name='branch',
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='branch',
            field=models.ManyToManyField(related_name='bank_credentials', to='app.branch'),
        ),
    ]
