# Generated by Django 5.1.2 on 2025-01-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_superadmin_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_telegram_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='superadmin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
