# Generated by Django 5.1.2 on 2025-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_staticpayment_com_id_staticpayment_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsersStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('telegram_language', models.CharField(max_length=10)),
                ('user_choose_language', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visiter', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message_id', models.CharField(default='messsage_id_123', max_length=20)),
            ],
            options={
                'db_table': 'qrjump_users_storage',
            },
        ),
        migrations.AlterField(
            model_name='staticpayment',
            name='branch',
            field=models.ManyToManyField(related_name='staticpayment', to='app.branch'),
        ),
    ]
