# Generated by Django 5.1.2 on 2025-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_staff_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_telegram_username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
