# Generated by Django 5.1.2 on 2025-01-30 06:49

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_staff_staff_telegram_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('aba', 'ABA Bank'), ('acleda', 'Acleda Bank'), ('wing', 'Wing Bank')], max_length=50)),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField(verbose_name=models.CharField(max_length=255))),
                ('public_key', encrypted_model_fields.fields.EncryptedTextField(verbose_name=models.CharField(max_length=255))),
                ('merchant_id', encrypted_model_fields.fields.EncryptedTextField(verbose_name=models.CharField(max_length=255))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_credentials', to='app.branch')),
            ],
            options={
                'db_table': 'qrjump_bank_credentials_storage',
                'unique_together': {('branch', 'bank_name')},
            },
        ),
    ]
