# Generated by Django 5.1.2 on 2025-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_botusersstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusersstorage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
