# Generated by Django 5.1.2 on 2025-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_botusersstorage_alter_staticpayment_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpayment',
            name='branch',
            field=models.ManyToManyField(related_name='statispayment', to='app.branch'),
        ),
    ]
