# Generated by Django 5.1.2 on 2025-02-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_botusersstorage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusersstorage',
            name='user_pin',
        ),
    ]
