# Generated by Django 5.1.2 on 2025-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bankcredentials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcredentials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
