# Generated by Django 5.1.2 on 2025-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_botusersstorage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpayment',
            name='branch',
            field=models.ManyToManyField(related_name='staticpayment', to='app.branch'),
        ),
    ]
